language: julia

os:
  - linux
  - osx

julia:
  - 0.4
  - 0.5
  - nightly

notifications:
  email: false

after_success:
  - julia -e 'include(Pkg.dir("MergedMethods", "test", "coverage.jl"))'
  - julia -e 'Pkg.add("Documenter"); Pkg.checkout("Documenter")'
  - julia -e 'cd(Pkg.dir("MergedMethods")); include(joinpath("docs", "make.jl"))'
